// ===================================
// JOB NOTIFICATION TRACKER
// Realistic Indian Tech Jobs Dataset
// ===================================

const jobsData = [
    // Internships & Freshers
    {
        id: 1,
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Python", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://flipkart.com/careers/apply/sde-intern-001",
        description: "Looking for passionate engineering students to join our tech team. You'll work on real-world problems at scale, build features used by millions, and learn from experienced engineers. Strong coding skills and problem-solving ability required."
    },
    {
        id: 2,
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML", "CSS"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://razorpay.com/careers/frontend-intern-002",
        description: "Join our frontend team to build beautiful, responsive web applications. You'll work with React, modern JavaScript, and collaborate with designers to create seamless user experiences. Portfolio with sample projects preferred."
    },
    {
        id: 3,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Basic Programming"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "3.6–4.5 LPA",
        applyUrl: "https://infosys.com/careers/get-trainee-003",
        description: "Comprehensive training program for fresh graduates. Learn enterprise technologies, work on client projects, and build your career with a global IT leader. Training includes Java, databases, and software development practices. 2024 graduates preferred."
    },
    {
        id: 4,
        title: "QA Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "API Testing"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹18k–₹28k/month Internship",
        applyUrl: "https://phonepe.com/careers/qa-intern-004",
        description: "Test our payment platform and ensure quality for millions of users. Learn automation testing, API testing, and work closely with developers. Attention to detail and analytical mindset essential."
    },
    {
        id: 5,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel", "Data Visualization"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://swiggy.com/careers/data-analyst-intern-005",
        description: "Analyze food delivery data to drive business insights. Work with large datasets, create dashboards, and support decision-making. Strong SQL and Python skills required. Knowledge of analytics tools is a plus."
    },

    // Junior Developers (0-1 years)
    {
        id: 6,
        title: "Java Developer",
        company: "TCS",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL", "REST APIs"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        applyUrl: "https://tcs.com/careers/java-dev-006",
        description: "Develop enterprise Java applications for global clients. Work with Spring Boot, microservices, and databases. Participate in code reviews and agile ceremonies. Freshers with strong Java fundamentals encouraged to apply."
    },
    {
        id: 7,
        title: "Python Developer",
        company: "Wipro",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "Django", "PostgreSQL", "Git"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://wipro.com/careers/python-dev-007",
        description: "Build backend services using Python and Django. Work on automation scripts, APIs, and database integration. Collaborate with cross-functional teams on enterprise projects. Good understanding of Object-Oriented Programming required."
    },
    {
        id: 8,
        title: "React Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["React", "JavaScript", "Redux", "CSS"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "5–7 LPA",
        applyUrl: "https://zoho.com/careers/react-dev-008",
        description: "Create intuitive user interfaces for our SaaS products. Work with React, state management, and modern frontend tools. Participate in design discussions and implement responsive web applications."
    },
    {
        id: 9,
        title: "Full Stack Developer",
        company: "Freshworks",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Node.js", "React", "MongoDB", "Express"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "6–9 LPA",
        applyUrl: "https://freshworks.com/careers/fullstack-009",
        description: "Build end-to-end features for our customer engagement platform. Work across the stack with modern JavaScript frameworks. Strong problem-solving skills and eagerness to learn new technologies required."
    },
    {
        id: 10,
        title: "Backend Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Go", "PostgreSQL", "Docker", "Kubernetes"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "8–12 LPA",
        applyUrl: "https://cred.club/careers/backend-010",
        description: "Design and develop scalable backend services for our fintech platform. Work with Go, distributed systems, and cloud infrastructure. Fast-paced startup environment with strong engineering culture."
    },

    // Mid-level (1-3 years)
    {
        id: 11,
        title: "Senior Frontend Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–15 LPA",
        applyUrl: "https://paytm.com/careers/senior-frontend-011",
        description: "Lead frontend development for our e-commerce and payment features. Architect scalable React applications, mentor junior developers, and drive technical decisions. Strong TypeScript and modern frontend expertise required."
    },
    {
        id: 12,
        title: "Backend Engineer",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "AWS", "DynamoDB", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://amazon.jobs/backend-engineer-012",
        description: "Build highly scalable distributed systems for Amazon's e-commerce platform. Design microservices, optimize performance, and ensure reliability. Experience with AWS and distributed systems architecture preferred."
    },
    {
        id: 13,
        title: "DevOps Engineer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "Jenkins", "AWS"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "12–18 LPA",
        applyUrl: "https://juspay.in/careers/devops-013",
        description: "Manage cloud infrastructure and CI/CD pipelines for our payment gateway. Automate deployments, monitor systems, and ensure high availability. Strong knowledge of containerization and orchestration required."
    },
    {
        id: 14,
        title: "Mobile App Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "iOS", "Android"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://dunzo.com/careers/mobile-014",
        description: "Develop cross-platform mobile applications using React Native. Implement new features, optimize app performance, and work closely with product teams. Experience shipping apps to App Store and Play Store required."
    },
    {
        id: 15,
        title: "Data Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Spark", "Kafka", "Airflow"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://ola.com/careers/data-engineer-015",
        description: "Build data pipelines to process terabytes of ride and driver data. Work with big data technologies, design ETL workflows, and support analytics teams. Strong programming and data modeling skills essential."
    },

    // Service Companies
    {
        id: 16,
        title: "SAP ABAP Developer",
        company: "Accenture",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SAP ABAP", "HANA", "Fiori", "OData"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "8–12 LPA",
        applyUrl: "https://accenture.com/careers/sap-abap-016",
        description: "Develop and customize SAP applications for enterprise clients. Work on ABAP programs, perform testing, and support implementations. SAP certification is a plus. Travel to client locations may be required."
    },
    {
        id: 17,
        title: "ServiceNow Developer",
        company: "Capgemini",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["ServiceNow", "JavaScript", "ITSM", "ITOM"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9–14 LPA",
        applyUrl: "https://capgemini.com/careers/servicenow-017",
        description: "Configure and customize ServiceNow platform for IT service management. Develop workflows, integrations, and custom applications. Work with global teams on enterprise ITSM projects."
    },
    {
        id: 18,
        title: "Salesforce Developer",
        company: "Cognizant",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Salesforce", "Apex", "Lightning", "SOQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "7–11 LPA",
        applyUrl: "https://cognizant.com/careers/salesforce-018",
        description: "Customize Salesforce CRM for enterprise customers. Develop Apex classes, Lightning components, and manage integrations. Salesforce certifications preferred. Opportunity to work on diverse projects."
    },
    {
        id: 19,
        title: "Oracle DBA",
        company: "IBM",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Oracle", "PL/SQL", "Database Tuning", "Backup/Recovery"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "8–13 LPA",
        applyUrl: "https://ibm.com/careers/oracle-dba-019",
        description: "Manage and optimize Oracle databases for mission-critical applications. Perform backup/recovery, tuning, and troubleshooting. On-call support rotation required. Strong SQL and database administration skills essential."
    },
    {
        id: 20,
        title: ".NET Developer",
        company: "Dell",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C#", ".NET Core", "Azure", "SQL Server"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "9–15 LPA",
        applyUrl: "https://dell.com/careers/dotnet-020",
        description: "Build enterprise applications using .NET technologies. Work on microservices, cloud deployments, and API development. Collaborate with global teams and follow agile methodologies."
    },

    // More Startups & Product Companies
    {
        id: 21,
        title: "Backend Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Django", "Redis", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://meesho.com/careers/backend-021",
        description: "Scale our social commerce platform serving millions of resellers. Build APIs, optimize database queries, and ensure system reliability. Strong backend fundamentals and problem-solving skills required."
    },
    {
        id: 22,
        title: "iOS Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "UIKit", "SwiftUI", "Core Data"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "14–22 LPA",
        applyUrl: "https://zomato.com/careers/ios-022",
        description: "Develop the Zomato iOS app used by millions of food lovers. Write clean Swift code, implement pixel-perfect UIs, and optimize app performance. Published apps on App Store strongly preferred."
    },
    {
        id: 23,
        title: "Android Developer",
        company: "Udaan",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Jetpack Compose", "MVVM", "Retrofit"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "11–17 LPA",
        applyUrl: "https://udaan.com/careers/android-023",
        description: "Build native Android experiences for B2B commerce. Implement modern architecture patterns, write testable code, and ship features rapidly. Strong Kotlin and Android SDK knowledge required."
    },
    {
        id: 24,
        title: "Machine Learning Engineer",
        company: "Navi",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "Scikit-learn", "MLOps"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "15–24 LPA",
        applyUrl: "https://navi.com/careers/ml-engineer-024",
        description: "Build ML models for credit scoring and risk assessment. Work on NLP, fraud detection, and personalization. Deploy models to production and monitor performance. Strong math and coding skills essential."
    },
    {
        id: 25,
        title: "SRE Engineer",
        company: "BrowserStack",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Python", "Terraform", "Monitoring"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "13–20 LPA",
        applyUrl: "https://browserstack.com/careers/sre-025",
        description: "Ensure reliability and performance of our testing infrastructure. Automate operations, build monitoring systems, and respond to incidents. Strong Linux and scripting skills required."
    },

    // Mid-sized Companies
    {
        id: 26,
        title: "Full Stack Developer",
        company: "Chargebee",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Ruby on Rails", "React", "PostgreSQL", "Redis"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        applyUrl: "https://chargebee.com/careers/fullstack-026",
        description: "Develop subscription billing features for global SaaS companies. Work across the stack with Rails and React. Solve complex domain problems and scale for growth."
    },
    {
        id: 27,
        title: "Security Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Security", "Penetration Testing", "OWASP", "AWS"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "14–22 LPA",
        applyUrl: "https://postman.com/careers/security-027",
        description: "Secure our API platform used by millions of developers. Perform security audits, implement best practices, and respond to vulnerabilities. Strong knowledge of application security required."
    },
    {
        id: 28,
        title: "QA Automation Engineer",
        company: "Innovaccer",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Python", "Cucumber", "CI/CD"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–13 LPA",
        applyUrl: "https://innovaccer.com/careers/qa-automation-028",
        description: "Build test automation frameworks for healthcare data platform. Write automated tests, integrate with CI/CD, and ensure quality. Experience with test frameworks and scripting essential."
    },
    {
        id: 29,
        title: "Data Scientist",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "R", "Statistics", "Machine Learning"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "12–19 LPA",
        applyUrl: "https://unacademy.com/careers/data-scientist-029",
        description: "Analyze learner data to improve educational outcomes. Build recommendation systems, run experiments, and create insights. Strong statistics and Python skills required."
    },
    {
        id: 30,
        title: "Product Engineer",
        company: "Clevertap",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "React", "Apache Kafka", "Elasticsearch"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "11–17 LPA",
        applyUrl: "https://clevertap.com/careers/product-engineer-030",
        description: "Build customer engagement and analytics platform. Work on real-time data processing, visualization, and APIs. Ownership of features end-to-end. Fast-paced product development environment."
    },

    // Additional Companies
    {
        id: 31,
        title: "Frontend Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "Redux", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–18 LPA",
        applyUrl: "https://groww.in/careers/frontend-031",
        description: "Create seamless investing experiences for millions of users. Build responsive web apps, optimize performance, and implement pixel-perfect designs. Strong React and JavaScript fundamentals required."
    },
    {
        id: 32,
        title: "Cloud Engineer",
        company: "Happiest Minds",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["AWS", "Terraform", "Docker", "Python"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "9–14 LPA",
        applyUrl: "https://happiestminds.com/careers/cloud-032",
        description: "Design and deploy cloud solutions on AWS. Work with infrastructure as code, containerization, and automation. AWS certifications preferred. Client-facing role with travel opportunities."
    },
    {
        id: 33,
        title: "Node.js Developer",
        company: "Pine Labs",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "Express", "MongoDB", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://pinelabs.com/careers/nodejs-033",
        description: "Build payment processing backend services. Design REST APIs, implement business logic, and ensure transaction reliability. Strong async programming and debugging skills essential."
    },
    {
        id: 34,
        title: "Angular Developer",
        company: "Mphasis",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "TypeScript", "RxJS", "NgRx"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "7–11 LPA",
        applyUrl: "https://mphasis.com/careers/angular-034",
        description: "Develop enterprise web applications using Angular. Implement complex UIs, manage state, and integrate with backend APIs. Work on banking and financial services projects."
    },
    {
        id: 35,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "18–28 LPA",
        applyUrl: "https://polygon.technology/careers/blockchain-035",
        description: "Build decentralized applications on Polygon network. Write smart contracts, develop dApps, and work on blockchain infrastructure. Strong understanding of Ethereum and Web3 ecosystem required."
    },

    // Senior Positions (3-5 years)
    {
        id: 36,
        title: "Staff Engineer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Java", "Microservices", "System Design", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "30–45 LPA",
        applyUrl: "https://phonepe.com/careers/staff-engineer-036",
        description: "Lead technical architecture for payment platform. Design scalable systems, mentor engineers, and drive technical excellence. Strong distributed systems experience and leadership skills required."
    },
    {
        id: 37,
        title: "Engineering Manager",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Leadership", "System Design", "Go", "Team Management"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "35–50 LPA",
        applyUrl: "https://razorpay.com/careers/em-037",
        description: "Manage engineering team building fintech products. Drive technical decisions, hire talent, and deliver features. Strong technical background and people management skills essential."
    },
    {
        id: 38,
        title: "Principal Architect",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Architecture", "System Design", "Java", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "40–60 LPA",
        applyUrl: "https://flipkart.com/careers/architect-038",
        description: "Define technical strategy for e-commerce platform. Design large-scale distributed systems, establish best practices, and guide engineering teams. Deep expertise in scalable architecture required."
    },
    {
        id: 39,
        title: "Lead Data Scientist",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Machine Learning", "Python", "Deep Learning", "MLOps"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "28–42 LPA",
        applyUrl: "https://ola.com/careers/lead-ds-039",
        description: "Lead ML initiatives for ride-hailing and logistics. Build predictive models, mentor data scientists, and drive ML adoption. PhD or strong research background preferred."
    },
    {
        id: 40,
        title: "Senior DevOps Engineer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        skills: ["Kubernetes", "AWS", "GitOps", "Observability"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "25–38 LPA",
        applyUrl: "https://swiggy.com/careers/senior-devops-040",
        description: "Build and scale infrastructure for food delivery platform. Implement GitOps, improve observability, and ensure reliability. Strong Kubernetes and cloud expertise required."
    },

    // More Diverse Roles
    {
        id: 41,
        title: "Technical Writer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Technical Writing", "API Documentation", "Markdown"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "8–14 LPA",
        applyUrl: "https://postman.com/careers/tech-writer-041",
        description: "Create comprehensive API documentation and developer guides. Work with engineers to document features and write tutorials. Strong writing skills and technical background required."
    },
    {
        id: 42,
        title: "UI/UX Engineer",
        company: "Clevertap",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Figma", "React", "CSS", "Design Systems"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        applyUrl: "https://clevertap.com/careers/uiux-042",
        description: "Bridge design and development. Create design systems, prototype interfaces, and implement pixel-perfect UIs. Both design and coding skills essential."
    },
    {
        id: 43,
        title: "Performance Engineer",
        company: "Myntra",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["JMeter", "Load Testing", "Performance Tuning", "Java"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "11–17 LPA",
        applyUrl: "https://myntra.com/careers/performance-043",
        description: "Ensure e-commerce platform performs under high load. Conduct load testing, identify bottlenecks, and optimize performance. Strong understanding of web applications and databases required."
    },
    {
        id: 44,
        title: "Site Reliability Engineer",
        company: "Walmart Labs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Linux", "Monitoring", "Incident Management"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "16–24 LPA",
        applyUrl: "https://walmartlabs.com/careers/sre-044",
        description: "Maintain reliability of retail systems serving millions. Build monitoring, automate operations, and manage incidents. On-call rotation required. Strong troubleshooting skills essential."
    },
    {
        id: 45,
        title: "Database Engineer",
        company: "SAP Labs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SAP HANA", "SQL", "Database Design", "Performance Tuning"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–19 LPA",
        applyUrl: "https://sap.com/careers/db-engineer-045",
        description: "Work on SAP HANA database platform. Optimize queries, design schemas, and support enterprise customers. Strong database fundamentals and SAP knowledge required."
    },

    // Additional Freshers & Internships
    {
        id: 46,
        title: "Graduate Engineer Trainee",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Basic Coding"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3.8–4.5 LPA",
        applyUrl: "https://cognizant.com/careers/get-046",
        description: "Join our comprehensive training program for fresh graduates. Learn enterprise technologies and work on real projects. Training covers programming, databases, and software engineering. Mass recruitment for 2024 batch."
    },
    {
        id: 47,
        title: "Software Developer Intern",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Cloud", "Databases"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "₹30k–₹40k/month Internship",
        applyUrl: "https://oracle.com/careers/intern-047",
        description: "Work on cloud infrastructure products. Learn from experienced engineers and contribute to production systems. Strong academic record and coding skills required. Potential for full-time conversion."
    },
    {
        id: 48,
        title: "Data Science Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Statistics", "Machine Learning", "SQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹40k–₹50k/month Internship",
        applyUrl: "https://amazon.jobs/ds-intern-048",
        description: "Apply ML to solve business problems at scale. Work with large datasets, build models, and present insights. Pursuing or recently completed degree in quantitative field. Strong programming and math skills required."
    },
    {
        id: 49,
        title: "Mobile Development Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Flutter", "Dart", "Mobile Development"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://zomato.com/careers/mobile-intern-049",
        description: "Build mobile features for food delivery app. Learn Flutter and work with experienced mobile developers. Portfolio with Flutter apps strongly preferred."
    },
    {
        id: 50,
        title: "Backend Intern",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Django", "REST APIs", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹35k–₹45k/month Internship",
        applyUrl: "https://meesho.com/careers/backend-intern-050",
        description: "Build backend services for social commerce platform. Work on APIs, databases, and microservices. Fast-paced startup environment with mentorship from experienced engineers."
    },

    // More Mid-level Opportunities
    {
        id: 51,
        title: "Product Manager - Tech",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Product Management", "SQL", "Analytics", "APIs"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "20–32 LPA",
        applyUrl: "https://cred.club/careers/pm-tech-051",
        description: "Drive product strategy for fintech features. Work with engineering, design, and business teams. Strong technical background and product sense required. MBA or engineering degree preferred."
    },
    {
        id: 52,
        title: "Infrastructure Engineer",
        company: "Uber",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Networking", "Automation", "Cloud"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "18–28 LPA",
        applyUrl: "https://uber.com/careers/infra-052",
        description: "Build and maintain infrastructure for ride-sharing platform. Automate operations, optimize costs, and ensure reliability. Strong systems and networking knowledge required."
    },
    {
        id: 53,
        title: "Test Automation Lead",
        company: "Wipro",
        location: "Pune",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Selenium", "Java", "Test Frameworks", "CI/CD"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "15–22 LPA",
        applyUrl: "https://wipro.com/careers/test-lead-053",
        description: "Lead test automation initiatives for enterprise clients. Design frameworks, mentor QA engineers, and drive quality practices. Strong automation and leadership skills required."
    },
    {
        id: 54,
        title: "Solutions Architect",
        company: "Tech Mahindra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Cloud Architecture", "AWS", "Azure", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "18–28 LPA",
        applyUrl: "https://techmahindra.com/careers/solutions-architect-054",
        description: "Design cloud solutions for enterprise customers. Create architecture diagrams, evaluate technologies, and guide implementations. Strong consulting and technical skills required."
    },
    {
        id: 55,
        title: "Security Analyst",
        company: "Barclays",
        location: "Pune",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Cybersecurity", "SIEM", "Threat Detection", "Incident Response"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "12–18 LPA",
        applyUrl: "https://barclays.com/careers/security-analyst-055",
        description: "Monitor and respond to security threats for banking systems. Analyze logs, investigate incidents, and implement security controls. Cybersecurity certifications preferred."
    },

    // Final Set
    {
        id: 56,
        title: "Game Developer",
        company: "Moonactive",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Unity", "C#", "Game Development", "3D Graphics"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "14–22 LPA",
        applyUrl: "https://moonactive.com/careers/game-dev-056",
        description: "Develop mobile games played by millions. Work with Unity, implement game mechanics, and optimize performance. Portfolio with shipped games strongly preferred."
    },
    {
        id: 57,
        title: "Embedded Systems Engineer",
        company: "Bosch",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "C++", "Embedded Systems", "RTOS"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "9–15 LPA",
        applyUrl: "https://bosch.com/careers/embedded-057",
        description: "Develop firmware for automotive and IoT devices. Work with microcontrollers, write low-level code, and test embedded systems. Strong C/C++ and hardware knowledge required."
    },
    {
        id: 58,
        title: "Business Analyst",
        company: "Deloitte",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SQL", "Excel", "Tableau", "Requirements Analysis"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://deloitte.com/careers/ba-058",
        description: "Bridge business and technology for consulting projects. Gather requirements, analyze data, and create reports. Strong analytical and communication skills essential."
    },
    {
        id: 59,
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Networking", "CCNA", "Routing", "Switching"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "11–17 LPA",
        applyUrl: "https://cisco.com/careers/network-engineer-059",
        description: "Design and maintain network infrastructure. Configure routers, switches, and firewalls. Troubleshoot network issues and ensure connectivity. CCNA or CCNP certification required."
    },
    {
        id: 60,
        title: "Scrum Master",
        company: "LTI Mindtree",
        location: "Chennai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Agile", "Scrum", "Jira", "Facilitation"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "14–20 LPA",
        applyUrl: "https://ltimindtree.com/careers/scrum-master-060",
        description: "Facilitate agile practices for enterprise development teams. Conduct ceremonies, remove blockers, and coach teams. CSM certification and agile experience required."
    }
];
